<a href="https://colab.research.google.com/github/nickkraus52/MachineLearning/blob/main/HW5/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load the dataset into a Pandas DataFrame.

For this assignment I downloaded the dataset as a csv and imported it using read_csv, assigning the proper column names.

In [10]:
import pandas as pd
import numpy as np

cols = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness",
        "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Target"]
df = pd.read_csv("pima-indians-diabetes.csv", header=None, names=cols)

print('First 5 Elements:')
display(df.head())

First 5 Elements:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Target
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

## Inspecting the Dataset

I ran the info function on the Dataframe to see the columns and their datatypes. I recognized that all the columns were numerical data types, so no implicit missing values. I also ran the describe and value_counts functions to see which columns might be categorical features.

In [11]:
print('Column Names and Data Types:')
display(df.info())

print('\nData Statistical Distribution: ')
display(df.describe().T)

Column Names and Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Target                    768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

None

Data Statistical Distribution:

,count,mean,std,min,25%,50%,75%,max
Pregnancies,768.0,3.845052,3.369578,0.000,1.00000,3.0000,6.00000,17.00
Glucose,768.0,120.894531,31.972618,0.000,99.00000,117.0000,140.25000,199.00
BloodPressure,768.0,69.105469,19.355807,0.000,62.00000,72.0000,80.00000,122.00
SkinThickness,768.0,20.536458,15.952218,0.000,0.00000,23.0000,32.00000,99.00
Insulin,768.0,79.799479,115.244002,0.000,0.00000,30.5000,127.25000,846.00
BMI,768.0,31.992578,7.884160,0.000,27.30000,32.0000,36.60000,67.10
DiabetesPedigreeFunction,768.0,0.471876,0.331329,0.078,0.24375,0.3725,0.62625,2.42
Age,768.0,33.240885,11.760232,21.000,24.00000,29.0000,41.00000,81.00
Target,768.0,0.348958,0.476951,0.000,0.00000,0.0000,1.00000,1.00

In [12]:
for col in cols:
    print(f'\n{col} Distribution:')
    display(df[col].value_counts())

Pregnancies Distribution:

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

Glucose Distribution:

Glucose
100    17
99     17
125    14
111    14
106    14
       ..
56      1
169     1
149     1
65      1
190     1
Name: count, Length: 136, dtype: int64

BloodPressure Distribution:

BloodPressure
70     57
74     52
78     45
68     45
72     44
64     43
80     40
76     39
60     37
0      35
62     34
66     30
82     30
88     25
84     23
90     22
58     21
86     21
50     13
56     12
54     11
52     11
92      8
75      8
65      7
94      6
85      6
48      5
96      4
44      4
110     3
98      3
100     3
106     3
30      2
108     2
55      2
104     2
46      2
40      1
122     1
95      1
102     1
61      1
24      1
38      1
114     1
Name: count, dtype: int64

SkinThickness Distribution:

SkinThickness
0     227
32     31
30     27
27     23
23     22
33     20
18     20
28     20
31     19
19     18
39     18
29     17
26     16
37     16
25     16
22     16
40     16
35     15
41     15
15     14
36     14
17     14
20     13
24     12
42     11
13     11
21     10
34      8
46      8
38      7
12      7
45      6
11      6
14      6
16      6
43      6
10      5
44      5
47      4
48      4
50      3
49      3
54      2
7       2
52      2
8       2
60      1
51      1
56      1
63      1
99      1
Name: count, dtype: int64

Insulin Distribution:

Insulin
0      374
105     11
140      9
130      9
120      8
      ...
178      1
127      1
510      1
16       1
112      1
Name: count, Length: 186, dtype: int64

BMI Distribution:

BMI
32.0    13
31.6    12
31.2    12
0.0     11
32.4    10
        ..
44.6     1
24.1     1
41.2     1
49.3     1
46.3     1
Name: count, Length: 248, dtype: int64

DiabetesPedigreeFunction Distribution:

DiabetesPedigreeFunction
0.254    6
0.258    6
0.261    5
0.207    5
0.268    5
        ..
1.182    1
0.222    1
1.057    1
0.766    1
0.171    1
Name: count, Length: 517, dtype: int64

Age Distribution:

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
32    16
38    16
36    16
45    15
34    14
43    13
46    13
40    13
39    12
35    10
50     8
51     8
44     8
52     8
58     7
54     6
47     6
53     5
57     5
60     5
48     5
49     5
62     4
55     4
66     4
63     4
59     3
56     3
65     3
67     3
61     2
69     2
72     1
81     1
64     1
70     1
68     1
Name: count, dtype: int64

Target Distribution:

Target
0    500
1    268
Name: count, dtype: int64

## Imputing Missing or Implicit Values 
The method I used to import the dataset had every column imported as a numerical type without nulls included. Instead implicit missing values are stored as 0s in features that can't possibly be 0.

In [13]:
print('Values with 0: ')
display((df == 0).sum())

print('\nNull Values: ')
display(df.isnull().sum())

Values with 0:

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Target                      500
dtype: int64

Null Values:

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Target                      0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.base import clone

df = df.replace(0, np.nan)

imputer = SimpleImputer(strategy='median')

sample_df = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

print('\nNull Values: ')
display(sample_df.isnull().sum())

print('\nData Statistical Distribution: ')
display(sample_df.describe().T)

Null Values:

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Target                      0
dtype: int64

Data Statistical Distribution:

,count,mean,std,min,25%,50%,75%,max
Pregnancies,768.0,4.423177,2.980481,1.000,2.00000,4.0000,6.00000,17.00
Glucose,768.0,121.656250,30.438286,44.000,99.75000,117.0000,140.25000,199.00
BloodPressure,768.0,72.386719,12.096642,24.000,64.00000,72.0000,80.00000,122.00
SkinThickness,768.0,29.108073,8.791221,7.000,25.00000,29.0000,32.00000,99.00
Insulin,768.0,140.671875,86.383060,14.000,121.50000,125.0000,127.25000,846.00
BMI,768.0,32.455208,6.875177,18.200,27.50000,32.3000,36.60000,67.10
DiabetesPedigreeFunction,768.0,0.471876,0.331329,0.078,0.24375,0.3725,0.62625,2.42
Age,768.0,33.240885,11.760232,21.000,24.00000,29.0000,41.00000,81.00
Target,768.0,1.000000,0.000000,1.000,1.00000,1.0000,1.00000,1.00

## Building a Pipeline with Encoding and Scaling

First I import the modules to create the pipeline. I combine them into a single column transformer. I used the simple imputer with median strategy and a standard scaler for the numerical pipeline. I used a simple imputer with most frequent strategy and the one hot encoder for the categorical features.

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

X = df.drop(columns=['Target'])
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

num_pipeline = Pipeline([
    ('imputer', imputer),
    ('scaler', StandardScaler())
])

preprocessor = ColumnTransformer([
    ('pipe', num_pipeline, X.columns)
])

display(preprocessor)

ColumnTransformer(transformers=[('pipe',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='str'))])

## Training Models Hard Vs. Soft Classifiers (SVC/DT/LogisticRegression)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, RocCurveDisplay, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, BaggingClassifier, AdaBoostClassifier
from matplotlib import pyplot as plt

estimators = [
    ('svm', SVC(probability=True, kernel='rbf', random_state=42)),
    ('dt', DecisionTreeClassifier(max_depth=5, random_state=42)),
    ('lr', LogisticRegression(max_iter=1000, random_state=42))
]

hard_voting = Pipeline([
    ('preprocessor', clone(preprocessor)),
    ('voting', VotingClassifier(estimators=estimators, voting='hard'))
])

soft_voting = Pipeline([
    ('preprocessor', clone(preprocessor)),
    ('voting', VotingClassifier(estimators=estimators, voting='soft'))
])

models = {}
def evaluate_model(name, model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].set_title('Confusion Matrix')
    ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred), display_labels=['No Heart Disease', 'Heart Disease']).plot(ax=axes[0], cmap='Blues')

    auc = roc_auc_score(y_test, y_proba)
    RocCurveDisplay.from_predictions(y_test, y_proba, ax=axes[1], name=f"{name}")
    axes[1].plot([0, 1], [0, 1], "k--", alpha=0.5, label="Chance")
    axes[1].set_title(f"{name}: ROC curve")
    axes[1].legend(loc="lower right")
    plt.show()

    report = classification_report(y_test, y_pred, target_names=['No Diabetes', 'Diabetes'], output_dict=True)

    print(f'\nClassification Report for {name}:')
    print(classification_report(y_test, y_pred, target_names=['No Diabetes', 'Diabetes']))

    models[name] = {
        'Accuracy': report['accuracy'],
        'Precision': report['Diabetes']['precision'],
        'Recall': report['Diabetes']['recall'],
        'F1 Score': report['Diabetes']['f1-score'],
        "ROC-AUC": auc
    }